version: 2

sources:
  - name: store_sales
    database: AwsDataCatalog
    schema: store_sales_analytics
    description: "Raw tables produced by the AWS Lambda + S3 ETL pipeline"
    tables:
      - name: fact_orders
      - name: fact_order_items

